auth-server:
#  name:
  uri: http://localhost:1080/api/v1
#  redirect-uri:
#  grant-type: client_credentials
#  scopes:
  source:
    provider: application # aws|gcp|application|environment
    props:
#      project-id: 829240121195
#      region:
#      client-id-key: client_id
#      client-secret-key: client_secret
#      endpoint: http://192.168.100.98:4566
#      secret-name: auth-server-main-client-secrets
      client-id: 9835e498-eb18-4d7a-8e8e-230b2190df1f
      client-secret: 51469bf9-081f-4023-a391-b94877bb5b1b
