#auth-server:
#  enabled: true
#  name:
#  uri: http://localhost:1080/api/v1
#  redirect-uri:
#  scopes:
#  timeout: 300
#  source:
#    provider: application # aws|gcp|application|environment
#    props:
#      project-id:
#      region: us-east-1
#      client-id-key: client_id
#      client-secret-key: client_secret
#      end-point: http://localhost:4566
#      secret-name: auth-server-main-client-secrets
#      client-id:
#      client-secret:
