name: Build and Deploy to GCP - DEV
on:
  push:
    tags:
     - '*'
jobs:
  ci-cd:
    name: CI/CD
    uses: felipemenezesdm/general-deploy-actions/.github/workflows/github-maven-package.yml@develop
    secrets: inherit
    with:
      username: ${{ github.actor }}
