#name: Deploy maven package to GitHub Repository
#on:
#  push:
#    tags:
#     - '*'
#jobs:
#  ci-cd:
#    name: CI/CD
#    uses: felipemenezesdm/general-deploy-actions/.github/workflows/github-maven-package.yml@develop
#    permissions:
#      contents: read
#      packages: write
#    secrets: inherit
#    with:
#      username: ${{ github.actor }}
name: Deploy maven package to GitHub Repository
on:
  push:
    branches: develop
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Deploy
        run: mvn deploy -Drepo.usrnm="${{ github.actor }}" -Drepo.pswd="${{ github.token }}"
